version: 2

jobs:
  build-staging:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.7.4-node
    steps:
      - checkout
      - run:
          name: test project
          command: |
            npm install
            npm run test:unit

workflows:
  version: 2
  build-test:
    jobs:
      - build-staging